# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Lee Carmichael  
title: Senior Electrical Engineer
email: lscarmic@tva.gov
website: lscarmic.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: ileec
github_username:  lscarmic
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: lscarmic
linkedin_username: leecarmichael
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Lee and I'm a senior electrical engineer in Control Center Design and Speical Projects. Over 
  the past 16+ years I've worked to incrementally moderize TVA's telecommunication sytem. From extending last 
  mile communications to rural areas of the valley, to organizing and automating network device information and configurations, I 
  have always been looking for ways to apply innovatinve tech soluitions to really big workplace challenges. Working
  smarter to sqeeze the best outcomes from every project is the name of the game I play.

  The things that I currently have the most experience working with are: <mark>Python</mark> <mark>MongoDB</mark>
  <mark>JavaScript</mark> <mark>D3</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left # top-middle
        title: IP Address Management System Upgrade
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          # - title:  sproogen/modern-resume-theme
          #   icon: fab fa-github
          #   url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          TVA, and CCD&SP specifically, has always had a need to collect and organize IP address information. From spradsheets to
          MS Access to BlueCat Proteus, the organization has had suboptimal solutions in place for keeping the most fundamental
          records for a networking group.
        description: | # this will include new lines to allow paragraphs
          - Lead engineer on the transition to Infoblox DDI
          -- this 

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Tennessee Valley Authority
        link: tva.gov
        # link_text: boringcompany.com
        sub_title: Senior Electrical Engineer
        caption: December 2004 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: Naval Surface Warfare Center - Dahlgren, VA
        link: navsea.navy.mil/Home/Warfare-Centers/NSWC-Dahlgren/
        # link_text: boringcompany.com
        sub_title: Senior Electrical Engineer
        caption: December 2004 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networ

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Georgia Institute of Technology
        caption: 2020 - Present
        sub_title: MS, Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Georgia Tech offeres four areas of MS specialization. I've chosen Machine Learning while tailoring elective classes to 
          include topics in data visulaization with <mark>JavaScript</mark> and <mark>D3</mark>, statistical analysis and simulation in <mark>Python</mark> and <mark>Arena</mark>, as well as fundamental 
          computer systems topics such as operating systems

          - Current GPA: 4.0
      - layout: left
        title: Tennessee Technological University
        caption: 2002 - 2004
        sub_title: MS Electrical Engineering
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Georgia Tech offeres four areas of MS specialization. I've chosen Machine Learning while tailoring elective classes to 
          include data visulaization, statistic analysis and simulation, as well as fundamental computer system topics. 
      - layout: left
        title: Tennessee Technological University
        caption: 1996 - 2002
        sub_title: BS, Electrical Engineering
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Georgia Tech offeres four areas of MS specialization. I've chosen Machine Learning while tailoring elective classes to 
          include data visulaization, statistic analysis and simulation, as well as fundamental computer system topics.






  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
