# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico
# https://github.com/sproogen/modern-resume-theme/blob/master/README.md

# Content configuration version
version: 2

# Personal info
name: Lee Carmichael  
title: Electrical Engineer/Rotational PMTM
email: lscarmic@tva.gov
website: lscarmic.github.io

# Dark Mode (true/false/never)
darkmode: never
# true = site will show the dark theme for everyone
# false = site will not show the dark theme, but it will still respect the users device preferences
# never = site will never be shown in the dark theme

# Social links
twitter_username: ileec
github_username:  lscarmic
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: lscarmic
linkedin_username: leecarmichael
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-D216D2D80L"
# google_analytics: "G-D216D2D80L"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Lee and I'm an electrical engineer currently on rotation with the Asset Performance Center here 
  at TVA. Over the past 17+ years, I've worked to incrementally modernize TVA's telecommunication system. From extending last 
  mile communications to rural areas of the valley, to organizing and automating network device information and configurations, I 
  have always been looking for ways to apply innovative tech solutions to really big workplace challenges. Working
  smarter to squeeze the best outcomes from every project is the name of the game I play.

  As you'll see below, an interest in using data and automation tools to tackle big problems has led me back to an 
  academic setting with the goal of formalizing my knowledge in the space of data analytics, machine learning, and, 
  in general, computer programming. As important as any concrete skill, the desire to be a continual learner has been 
  a central theme of my life. I firmly believe having sharp tools is important to doing great work. 

  I've continued this approach into my current rotation where, as a Program Manager, Transmission Maintenance, I've used some of the 
  same tools, as well as some new ones, to ensure reliable transmission system operation and efficient utilization of resources. 

  The things that I currently have the most experience working with are:  <mark>PowerBI</mark> <mark>Hitachi Lumada/APM</mark> <mark>eDNA</mark>  
  <mark>SysAid</mark> <mark>Python</mark> <mark>Linux/Unix/OSX</mark>

content:
  - title: Major Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left # top-middle
        title: APM Data Cleanup and Reporting
        sub_title: 
        description: | # this will include new lines to allow paragraphs
          The <mark>Hitachi Lumada/APM</mark> software used by the APC integrates data from several data stores at TVA. Inconsistencies in external data 
          have created large amounts of data cleanup inside Lumada/APM . Tools like <mark>Microsoft PowerBI</mark> allow us to quickly pinpoint data
          problems so they can be resolved easily. 

          - Leveraged <mark>PowerBI</mark> to identify incorrect bushing data on all relevant transformers and breakers. 

          PowerBI has also allowed the APC to offer custom reporting to device SMEs. 
          
          - Leveraged <mark>PowerBI</mark> to show historic trends of combustible gasses on 161KV Westinghouse Transformers, a very specific 
          report request that would be otherwise impossible to provide.
          - Leverage <mark>PowerBI</mark> to better understand my own asset management, asset lifecycle, and condition monitoring responsibilities.
          Occasionally I'm able to provide information to colleagues that expedites their own data cleanup and issue tracking efforts.

      - layout: left # top-middle
        title: SysAid-APM Integrations
        sub_title: 
        description: | # this will include new lines to allow paragraphs
          A great deal of work has been dedicated to modifying TVA's <mark>SysAid</mark> ticketing system to include for support asset condition ticketing
          as well as normal network operations ticketing. A ticket reporting feature was added to Lumada/APM assets to allow quick 
          ticketing summaries for any device.

          - Gained understanding of the <mark>SysAid API</mark> and <mark>PowerBI</mark> dataflows provided by other organizations, as well as 
          Lumada/APM limitations and workarounds.
          - Provided multiple approaches and solutions for integrating ticket data into Lumada/APM. 

          Also served on a team to roll out asset condition ticketing to the TVA field organizations. This initiative is working to 
          gain buy-in and coordination between various TVA entities to ensure asset issues are communicated effectively and in such a 
          way that asset condition trends can be managed to ensure optimum operation and reliability of the TVA transmission system.

      - layout: left # top-middle
        title: CCVT Failure Inquiry
        sub_title: 
        description: | # this will include new lines to allow paragraphs
          CCVT failures have plagued TVA for years. As a very light exposure to the problem and the work involved to extract
          meaning from the current data, I completed a small and unofficial rotational assignment prior to the current official rotational 
          assignment.

          - Gained a good understanding of TVA's <mark>eDNA</mark> data historian and the limitations of the contained data.
          - Gained exposure to the <mark>Avantis PRiSM</mark> tool as a method for analyzing data.

          While short, this was a great introductory look at TVA's data and available analytics systems. 

      - layout: left # top-middle
        title: Modernizing Meter Communications
        description: | # this will include new lines to allow paragraphs
          Metering Services and Power Billing have always had a need for a stand-alone, low-cost networking solution for simple
          meter interrogation. A capable router equipped with a cellular interface turned out to be the perfect solution.

          - Lead engineer on the initial installation of nearly 1,000 3G cellular routers.
          - Designed and orchestrated the move of the devices from the public Internet to a private wireless solution.
          - Designed and orchestrated the move from 3G to 4G cellular.
          - Implemented and configured the vendor system for asset tracking and monitoring.
          - Acted as the liaison between TVA and the device manufacture to identify and diagnose issues, as well as integrate 
          and implement any required fix.
          - Implemented zero-touch provisioning (ZTP) system for 700 new 4G devices. The move to 4G coincided with much of the 
          network automation efforts within CCD&SP (see below), thus I was able to leverage my own Python expertise 
          to implement a ZTP system. This reduced per-device configuration and installation time from hours to minutes, saving TVA 
          huge amounts of time and energy.
    
      - layout: left # top-middle
        title: Network Automation and MongoDB
        description: | # this will include new lines to allow paragraphs
          Stemming from accomplishments of cleaning data in the CCD&SP IP address management system, the realization was
          made that more sophisticated tasks could be carried out using programmatic techniques.

          - Lead engineer on proof-of-concept, selection, and implementation of MongoDB as a fast and scalable database 
          for network device information.
          - Lead developer of solutions for programmatically querying, verifying, and recording device properties and configuration details.
          These capabilities have directly lead to authoritative knowledge of telecommunications system assets for quick and accurate reporting to 
          compliance agencies regarding various security inquiries. 

      - layout: left # top-middle
        title: IP Address Management System Upgrade
        description: | # this will include new lines to allow paragraphs
          TVA Transmission has always had a need to collect and organize large amounts of IP address information. From spreadsheets to
          Microsoft Access to BlueCat Proteus, suboptimal implementations of various solutions have been in place with the sole purpose
          of being an accurate information repository. The resulting data inaccuracies have led to countless hours of work discovering 
          and correcting addressing mistakes that could have easily been avoided.

          - Lead engineer on the transition to Infoblox DDI.
          - Included cleanup of vast amounts of data inaccuracies (~60% -> 95+% accuracy improvements) across nearly 8,000 networks containing
          18,000 devices and nearly 25,000 individual host IP addresses.
          - Developed a Python library that interfaced with the Infoblox API to automate the initial population of the new IPAM system.
          - Leveraged the library to streamline continuous data management and reporting, including a simplified Django powered web interface 
          for field personnel.

      - layout: left # top-middle
        title: LPC Interruptible Product (IP) and Flexibility Programs
        description: | # this will include new lines to allow paragraphs
          TVA has offered IP products to provide customers with an opportunity to receive monthly credits on their power bill in 
          exchange for curtailing their power usage to a specified protected demand amount during times of TVA power system need. 
          Similarly, generation partners have been given the opportunity to generate up to 5% of their average electric needs from 
          distributed resources. Both customer solutions require communications paths between TVA and the LPC metering point. 

          - Technical lead and point of contact between all LPCs and TVA. 
          - Worked hand-in-hand with TVA partners to ensure smooth device turn up, as well as technical support for any configuration
          questions or issues.
          - Operated the Transmission Test Lab endpoint for proof of concept and documentation of new gateway devices in support of Central
          Operations.
          - Acted as a technical representative between customers and their device manufacturers.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Tennessee Valley Authority
        link: tva.gov
        # link_text: boringcompany.com
        sub_title: Program Manager, Transmission Maintenance
        caption: May 2022 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Learned and operated <mark>Hitachi Lumada APM</mark> to monitor, understand, and provide action to over 6000 transmission system assets.
            - Gained deep understanding of the APIs and backends of TVA systems including <mark>Hitachi Lumada/APM</mark> and <mark>SysAid</mark>.
            - Extended my knowledge of <mark>PowerBI</mark> and transmission assets to provide actionable reporting for transmission SMEs, 
            field personnel, and other APC coordinators.
            - Gained understanding of asset monitoring hardware for effectiveness in turn-up and troubleshooting.

      - layout: left
        title: Tennessee Valley Authority
        link: tva.gov
        # link_text: boringcompany.com
        sub_title: Senior Electrical Engineer
        caption: December 2004 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Engineered and configured many telecommunication solutions for substation connectivity including fiber optic, microwave, satellite, and cellular
            technologies.
            - Engineered and configured many end devices in support of SCADA (supervisory control and data acquisition) including router, switches, RTUs, and IO modules.
            - Engineered and designed many substation support systems including 48 VDC battery systems.
            - 2009 PSO Employee of the Year
            - Participated in employee advocacy groups such as the PCS Employee Council. 
            - Represented my business unit in charity activities such as the Combined Federal Campaign and Day of Caring events.

      - layout: left
        title: Naval Surface Warfare Center - Dahlgren, VA
        link: navsea.navy.mil/Home/Warfare-Centers/NSWC-Dahlgren/
        link_text: NSWC - Dahlgren
        sub_title: Graduate Intern
        caption: 2002-2004
        description: | # this will include new lines to allow paragraphs
            Participated in IEEE 1541 wireless sensor working group meetings. Performed high-level performance testing of IEEE 802.11 technologies. 
            Characterized performance of Layer 2 survivability protocols in support of my Master's thesis.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Georgia Institute of Technology
        caption: 2020 - Present
        sub_title: MS, Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Georgia Tech offers four areas of MS specialization. I've chosen Machine Learning while tailoring elective classes to 
          include topics in data visualization with JavaScript and D3, statistical analysis and simulation in 
          Python and Arena, a discrete-event simulation tool, as well as fundamental computer systems topics 
          involving C programming core OS functionality such as threading, inter-process communication, and networking.

          - Current GPA: 4.0
          - Progress - 40% complete
          - Estimated completion date: Dec 2024 (pace is two classes per year)
      - layout: left
        title: Tennessee Technological University
        caption: 2002 - 2004
        sub_title: MS, Electrical Engineering
        description: | # this will include new lines to allow paragraphs
          TTU didn't offer explicit specialization areas, but my MS coursework and thesis topics centered around telecommunications, 
          digital systems, and computer networking. 

          - My thesis, "Comparison and Characterization of Modern Layer-2 Ethernet Survivability Protocols", looked at various modern 
          (at the time) methods for improving the reliability of computer networks. 

      - layout: left
        title: Tennessee Technological University
        caption: 1996 - 2002
        sub_title: BS, Electrical Engineering
        # # quote: >
        # #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          These were formative years, and form I did.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in computer hardware and software, some of my other interests and hobbies are:
      - Cycling - I ride and race bikes in the woods. I've done over 100 mountain bike races with a few road races sprinkled in
      for good measure. I started riding a little over 10 years ago and have managed to clock about 55,000 miles. Doing these physically 
      challenging events has been an obsession and I think I'm a better person for it.
      - Woodworking - Realizing I won't be remembered for my amateur cycling achievements, I took up the hobby of woodworking to turn
      my free time into a tangible result. I find it to be the perfect intersection of art and engineering. I only make furniture for 
      myself and have completed several large pieces including a chest of drawers, five chairs, and a few tables.
      - Being the best daddy to an 8-year old little girl that I can be. 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
