# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico
# https://github.com/sproogen/modern-resume-theme/blob/master/README.md

# Content configuration version
version: 2

# Personal info
name: Lee Carmichael  
title: Senior Electrical Engineer
email: lscarmic@tva.gov
website: lscarmic.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: ileec
github_username:  lscarmic
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: lscarmic
linkedin_username: leecarmichael
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Lee and I'm a senior electrical engineer in Control Center Design and Special Projects here at TVA. Over 
  the past 16+ years I've worked to incrementally modernize TVA's telecommunication system. From extending last 
  mile communications to rural areas of the valley, to organizing and automating network device information and configurations, I 
  have always been looking for ways to apply innovative tech solutions to really big workplace challenges. Working
  smarter to squeeze the best outcomes from every project is the name of the game I play.

  As you'll see below, an interest in using data and automation tools to tackle big problems has lead me back to a 
  academic setting with the goal of formalizing my knowledge in the space of data analytics, machine learning, and, 
  in general, computer programming. As important as any concrete skill has been the desire to continually learn throughout 
  my career. Having sharp tools is important to doing great work. 

  The things that I currently have the most experience working with are: <mark>Python</mark> <mark>MongoDB</mark>
  <mark>JavaScript</mark> <mark>D3</mark>

content:
  - title: Major Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left # top-middle
        title: Modernizing Meter Communications
        sub_title: 
        description: | # this will include new lines to allow paragraphs
          Metering Services and Power Billing have always had a need for a stand-alone low-cost networking solution for simple
          meter interrogation. A capable router equipped with a cellular interface turned out to be the perfect solution.

          - Lead engineer on the initial installation of nearly 1000 3G cellular routers.
          - Designed and orchestrated the move of the devices from the public Internet to a private wireless solution.
          - Designed and orchestrated the move from 3G to 4G cellular.
          - Implemented and configured the vendor system for asset tracking and monitoring.
          - Implemented zero-touch provisioning (ZTP) system for 700 new 4G devices. The move to 4G coincided with much of the 
          network automation efforts within CCD&SP (see below), thus I was able to leverage my own <mark>Python</mark> expertise 
          to implement a ZTP system. This reduced per device configuration and installation time from hours to minutes, saving TVA 
          huge amounts of time and energy.
    
      - layout: left # top-middle
        title: Network Automation and MongoDB
        sub-title: Infoblox API to <mark>MongoDB<MongoDB>
        description: | # this will include new lines to allow paragraphs
          Stemming from accomplishments of cleaning data in the CCD&SP IP address management system, the realization was
          made that more sophisticated tasks could be carried out using programmatic techniques.

          - Lead engineer on proof-of-concept, selection, and implementation of <mark>MongoDB<MongoDB</mark> as a fast and scalable database for network device
          information.
          - Lead developer of solutions for programmatically querying, verifying, and recording device properties and configuration details.
          These capabilities have directly lead to authoritative knowledge of the telecommunications system for quick and accurate reporting to 
          compliance agencies regarding various security inquiries. 
          

      - layout: left # top-middle
        title: IP Address Management System Upgrade
        sub-title: BlueCat Proteus to Infoblox DDI
        description: | # this will include new lines to allow paragraphs
          TVA Transmission has always had a need to collect and organize large amounts of IP address information. From spreadsheets to
          Microsoft Access to BlueCat Proteus, suboptimal implementations of various solutions have been in place with the sole purpose
          of being an accurate information repository. The resulting data inaccuracies have lead to countless hours of work discovering 
          and correcting addressing mistakes that could have easily been avoided.

          - Lead engineer on the transition to <mark>Infoblox DDI</mark>.
          - Included cleanup of vast amounts of data inaccuracies (~60% -> 95+% accuracy improvements) across nearly 8,000 networks containing
          18,000 devices and nearly 25,000 individual host IP addresses.
          - Developed a <mark>Python</mark> library that interfaced with the Infoblox API to automate the initial population of the new IPAM system.
          - Leveraged the library to streamline continuous data management and reporting, including a <mark>Django</mark> powered web interface 
          for field personnel.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Tennessee Valley Authority
        link: tva.gov
        # link_text: boringcompany.com
        sub_title: Senior Electrical Engineer
        caption: December 2004 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Engineered and configured many telecommunication solutions for substation connectivity including fiber optic, microwave, satellite, and cellular
            technologies.
            - Engineered and configured many end devices in support of SCADA (supervisory control and data acquisition) including RTUs, IO modules, and...
            - Engineered and designed many substation support systems including 48 VDC battery systems.
            - 2009 PSO Employee of the Year
            - Participated in employee advocacy groups such as the PCS Employee Council. 
            - Represented my business unit in charity activities such as the Combined Federal Campaign and Day of Caring events.

      - layout: left
        title: Naval Surface Warfare Center - Dahlgren, VA
        link: navsea.navy.mil/Home/Warfare-Centers/NSWC-Dahlgren/
        link_text: NSWC - Dahlgren
        sub_title: Graduate Intern
        caption: 2002-2004
        description: | # this will include new lines to allow paragraphs
            Participated in IEEE 1541 wireless sensor working group meetings. Performed high-level performance testing of IEEE 802.11 technologies. Characterized performance of Layer 2 survivability protocols.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Georgia Institute of Technology
        caption: 2020 - Present
        sub_title: MS, Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Georgia Tech offers four areas of MS specialization. I've chosen Machine Learning while tailoring elective classes to 
          include topics in data visualization with <mark>JavaScript</mark> and <mark>D3</mark>, statistical analysis and simulation in 
          <mark>Python</mark> and <mark>Arena</mark>, a discrete-event simulation tool, as well as fundamental computer systems topics 
          that have involved <mark>C</mark> programming core OS functionality such as threading, inter-process communication, and networking.

          - Current GPA: 4.0
          - Progress - 40% complete
          - Estimated completion date: Dec 2024 (pace is two classes per year)
      - layout: left
        title: Tennessee Technological University
        caption: 2002 - 2004
        sub_title: MS, Electrical Engineering
        description: | # this will include new lines to allow paragraphs
          TTU didn't offer explicit specialization areas, but my MS coursework and thesis topics centered around telecommunications, 
          digital systems, and computer networking. 

          - My thesis, "Comparison and Characterization of Modern Layer-2 Ethernet Survivability Protocols", looked at various modern 
          (at the time)methods for improving the reliability of computer networks. 

      - layout: left
        title: Tennessee Technological University
        caption: 1996 - 2002
        sub_title: BS, Electrical Engineering
        # # quote: >
        # #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          These were formative years, and form I did.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in computer hardware and software, some of my other interests and hobbies are:
      - Cycling - I ride and race bikes in the woods. I've done over 100 mountain bike races with a few road races sprinkled in
      for good measure. I started riding a little over 10 years ago and have managed to clock about 55,000 miles. It has been an 
      obsession with doing physically challenging events and I think I'm a better person for it.
      - Woodworking - Realizing I won't be remembered for my amateur cycling achievements, I took up the hobby of woodworking to turn
      my free time into a tangible result. I find it to be the perfect intersection of art and engineering. I only make furniture for 
      myself and have completed several large pieces including a chest of drawers, five chairs, and a few tables.
      - Being the best daddy to an 8-year old little girl that I can be. 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
